[base]
# The color for mistyped or missing commands (Error)
unknown-token = 9

# The colors for valid commands (Positive)
# We set all four types so aliases and built-ins match regular commands
command       = 10
alias         = 10
builtin       = 10
function      = 10
